Class Interface {
    [string]$Name
    [string]$Comment
    [string]$IpAddress
    [string]$MacAddress
    [string]$Id
    [string]$Nameif
    [int]$SecurityLevel
    [int]$Speed
    [string]$Duplex
    [string]$AccessList
    [string]$AccessListDirection
    [string]$Vdom
    [bool]$IsDhcpClient
    [string[]]$AllowedMgmtMethods
    [int]$VlanId
    [string]$ParentInterface
    [string]$InterfaceType
    [string[]]$AggregateMember
    [bool]$IsManagement
    [bool]$IsPPPoE
    [bool]$Disabled
    [string]$Role
}
